version: '3.9'

services:
    server:
      build: 
        context: .
      container_name: probe_server
      restart: always
      ports:
        - 8000:8000
      depends_on:
        - db
      env_file:
        - .env

    db:
      image: mysql:latest
      restart: always
      container_name: probe_db
      volumes:
        - ./docker/initdb:/docker-entrypoint-initdb.d
        - ./mysql_volume:/var/lib/mysql/
      env_file:
        - .env
    
    pma:
      image: phpmyadmin:latest
      container_name: probe_pma
      restart: always
      ports:
        - 8080:80
      logging:
        driver: none
      env_file:
        - .env

